// real_client/spelling-correction-react/src/App.js
import './App.css';
import Axios from 'axios'
import { useState, useEffect } from 'react'

function App() {
  const [corpus, setCorpus] = useState([]);
  const [searchList, setSearchList] = useState([]);
  const [isSearch, setIsSearch] = useState(false);

  const getCorpusList = () => {
    Axios.get("http://localhost:8000/api/corpustokens").then((response) => {
      console.log(response)
      console.log(response.data)
      setCorpus(response.data.result)
      console.log(corpus)
    })
  }

  const postSpellCheck = () => {
    
    Axios.post("http://localhost:8000/api/corpustokens")
  }

  const searchInCorpus = (event) => {
    event.preventDefault()
    let value = document.getElementById('query').value
    let newArray = []
    corpus.map((word, key) => {
      if (word.includes(value)) {
        newArray.push(word.toLowerCase())
      }
    })
    setSearchList(newArray.slice(0, 999).sort())
    setIsSearch(true)
  }

  useEffect(() => {
    getCorpusList()
  }, [])

  return (
    <>
      <div className="container">
        <h2>Real Time Spelling Correction App</h2>
        <p className="main">
          Check your English text for grammar, spelling, and punctuation errors
          with our spelling correction app.
        </p>

        <div className="content-wrapper">
          <div>
            <div className="box-container">
              <textarea
                id="textarea"
                className="textarea"
                placeholder="Type Something..."
                maxLength="500"
              ></textarea>
              <div className="corpus-list">
                <ul className="scroll" id="corpus-ul">
                  {!isSearch ?
                    corpus.slice(0, 999).map((word, key) => {
                      return <li id={key}>{word}</li>
                    })
                    : searchList.slice(0, 99).map((word, key) => {
                      return <li id={key}>{word}</li>
                    })
                  }
                </ul>
                <form className="search-form" id="form" role="search" >
                  <input className='search-input' type="search" id="query" name="q"
                  placeholder="Search..."
                  aria-label="Search through site content" />
                  <button className="search-button" id="search-but" onClick={searchInCorpus}>Search</button>
                </form>
              </div>
            </div>

            <button className='check-button'>Spell Check</button>

            <div className="counter-container">
              <p>Total character: <span id="total-conter"> 0</span></p>
              <p>
                Remaining:
                <span className="remaining-counter" id="remaining-counter">500</span>
              </p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

export default App;

// real_client/spelling-correction/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder } from '@angular/forms';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})

export class AppComponent{
  searchForm: any;
  title = 'spelling-correction';

  

  /*
  constructor(private formBuilder: FormBuilder){
    this.searchForm = this.searchForm.group({
      search: '',
    })
  }*/


  
  ngOnInit(): void {}

  ngAfterViewInit() {
    var charval = <HTMLTextAreaElement>document.getElementById("textarea")
    let totalCount = document.getElementById("total-conter") as HTMLSpanElement;
    let remainingCoutn = document.getElementById("remaining-counter") as HTMLSpanElement;

    let userChar = 0;

    // to update the character on screen
    const updateCounter = () => {
      userChar = charval.value.length;

      totalCount.innerText = userChar.toString();

      remainingCoutn.innerText = (500 - userChar).toString();
    };

    charval.addEventListener("keyup", () => updateCounter());

    // to copy the text
    const copyText = () => {
      charval.select();
      charval.setSelectionRange(0, 99999);
      navigator.clipboard.writeText(charval.value);
    };
    
    // Search Function
    var input = <HTMLInputElement>document.getElementById('my-input')
    var inputValue = input.value.toUpperCase()
    var theUl = document.getElementById('corpus-ul')
    var theLi = theUl?.getElementsByTagName('li') as HTMLCollectionOf<HTMLElement>
    var button = <HTMLButtonElement>document.getElementById('search-but')

    button.addEventListener('click', function() {
      for (let i=0; i < theLi?.length; i++) {
        let textValue = theLi[i].textContent || theLi[i].innerHTML
        if (textValue.toUpperCase().indexOf(inputValue) > -1) {
          theLi[i].style.display = "";
        } else {
          theLi[i].style.display = "none";
        }
      }
    })
  }
  

}

<div class="container">
  <h2>Real Time Spelling Correction App</h2>
  <p class="main">
    Check your English text for grammar, spelling, and punctuation errors
    with our spelling correction app.
  </p>

  <div class="content-wrapper">
    <div>
      <div class="box-container">
        <textarea
          id="textarea"
          class="textarea"
          placeholder="Type Something..."
          maxlength="500"
        ></textarea>
        <div class="corpus-list">
          <ul class="scroll" id="corpus-ul">
            <li>apple</li>
            <li>anchor</li>
            <li>ashes</li>
            <li>bay</li>
            <li>buy</li>
            <li>bamboo</li>
            <li>best</li>
            <li>bake</li>
            <li>text</li>
            <li>text</li>
            <li>text</li>
            <li>text</li>
            <li>text</li>
            <li>text</li>
            <li>text</li>
            <li>text</li>
            <li>text</li>
            <li>text</li>
            <li>text</li>
            <li>text</li>
            <li>text</li>
          </ul>
          <form class="search-form" id="form" role="search" >
            <input class='search-input' type="search" id="query" name="q"
             placeholder="Search..."
             aria-label="Search through site content" id="my-input">
            <button class="search-button" id="search-but">Search</button>
          </form>
        </div>
      </div>

      <button class='check-button' onclick="copyText()">Spell Check</button>

      <div class="counter-container">
        <p>Total character: <span id="total-conter"> 0</span></p>
        <p>
          Remaining:
          <span class="remaining-counter" id="remaining-counter">500</span>
        </p>
      </div>
    </div>
  </div>
</div>
